### ISSUE TITLE
请问，对您的源码我们能做什么和不能做什么？

### ISSUE THREAD

**Issue by cupen** [yesunsong/U8SDK#1]
打扰啦，暂未看到您发表公共授权协议，有点不敢轻举妄动。
也许您脑海里有个类似 MIT, LGPL 或者 BSD 授权协议正打算公布呢？

**Comment by yesunsong** [comment]
您好，这是我在学习别人的U8SDK建立的项目。有兴趣的话，可以度娘 U8SDK就可以找到。

**Comment by cupen** [comment]
啊~  抱歉忘了回。
谢谢回应，我以为是 u8sdk 开源了客户端源码，误会误会。
